### 회원 정보 삭제1
DELETE /members/naht94
Host: localhost:9090


### 회원 정보 삭제2
DELETE /members/suebin
Host: localhost:9090


### 회원 정보 생성1
POST /members
Host: localhost:9090
Content-Type: application/json

{
    "memberId" : "naht94",
    "password" : "1111",
    "email" : "naht94@hanmail.net",
    "name" : "권형택"
}


### 회원 정보 생성2
POST /members
Host: localhost:9090
Content-Type: application/json

{
    "memberId" : "suebin",
    "password" : "2222",
    "email" : "suebin@gamil.com",
    "name" : "오수빈"
}

### 회원 정보 목록 조회
GET /members
Host: localhost:9090

### 회원 정보 단건 조회1
GET /members/naht94
Host: localhost:9090


### 회원 정보 단건 조회2
GET /members/suebin
Host: localhost:9090

### 회원 정보 단건 조회 email1
GET /members/email/suebin@gmail.com
Host: localhost:9090


### 회원 정보 수정1
PUT /members/naht94
Host: localhost:9090
Content-Type: application/json

{
  "password" : "3333",
  "email" : "gw0406@naver.com",
  "name" : "장현준"
}

### 회원 정보 수정2
PUT /members/suebin
Host: localhost:9090
Content-Type: application/json

{
  "password" : "3333",
  "email" : "gw0406@naver.com",
  "name" : "장현준"
}